"""Tests for KBE issue body parsing.

The parser must extract hit counts, error details, and build links
from GitHub issue bodies that contain markdown tables generated by
the KBE automation.

Functions under test (from scripts.fetch_issues):
    parse_hit_counts(body: str) -> HitCounts
    parse_error_pattern(body: str) -> Optional[str]
    parse_build_link(body: str) -> Optional[str]
"""

import sys
import os
import pytest

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))
from scripts.fetch_issues import parse_hit_counts, parse_error_pattern, parse_build_link


# =========================================================================
# HIT COUNT PARSING — WELL-FORMED BODIES
# =========================================================================


class TestWellFormedBody:
    """Standard KBE body with all expected fields."""

    def test_extracts_all_hit_counts(self, sample_issue_body_well_formed):
        result = parse_hit_counts(sample_issue_body_well_formed)
        assert result.hits_24h == 12
        assert result.hits_7d == 87
        assert result.hits_30d == 342

    def test_minimal_body(self, sample_issue_body_minimal):
        result = parse_hit_counts(sample_issue_body_minimal)
        assert result.hits_24h == 5
        assert result.hits_7d == 42
        assert result.hits_30d == 180

    def test_zero_counts(self, sample_issue_body_zero_counts):
        result = parse_hit_counts(sample_issue_body_zero_counts)
        assert result.hits_24h == 0
        assert result.hits_7d == 0
        assert result.hits_30d == 0


# =========================================================================
# WHITESPACE & FORMATTING VARIATIONS
# =========================================================================


class TestWhitespaceHandling:
    """Tables with extra whitespace, padding, or formatting quirks."""

    def test_extra_whitespace(self, sample_issue_body_extra_whitespace):
        result = parse_hit_counts(sample_issue_body_extra_whitespace)
        assert result.hits_24h == 5
        assert result.hits_7d == 42
        assert result.hits_30d == 180

    def test_commas_in_counts(self, sample_issue_body_commas_in_counts):
        """Hit counts formatted with thousands separators: 1,234."""
        result = parse_hit_counts(sample_issue_body_commas_in_counts)
        assert result.hits_24h == 1234
        assert result.hits_7d == 5678
        assert result.hits_30d == 12345


# =========================================================================
# MISSING / MALFORMED DATA
# =========================================================================


class TestMalformedBody:
    """Bodies with missing tables, missing columns, or garbled content."""

    def test_no_table_defaults_to_zero(self, sample_issue_body_malformed):
        result = parse_hit_counts(sample_issue_body_malformed)
        assert result.hits_24h == 0
        assert result.hits_7d == 0
        assert result.hits_30d == 0

    def test_empty_body(self):
        result = parse_hit_counts("")
        assert result.hits_24h == 0
        assert result.hits_7d == 0
        assert result.hits_30d == 0

    def test_none_body(self):
        """None passed as body — parse_hit_counts checks 'if not body'."""
        result = parse_hit_counts(None)
        assert result.hits_24h == 0
        assert result.hits_7d == 0
        assert result.hits_30d == 0

    def test_missing_column(self, sample_issue_body_missing_column):
        """Table with only 2 columns — regex needs 3 groups, should fail to match."""
        result = parse_hit_counts(sample_issue_body_missing_column)
        # With only 2 columns the regex won't match → defaults to 0
        assert result.hits_24h == 0
        assert result.hits_7d == 0
        assert result.hits_30d == 0


# =========================================================================
# MULTIPLE TABLES
# =========================================================================


class TestMultipleTables:
    """Body containing several markdown tables — parser picks the KBE one."""

    def test_selects_kbe_table(self, sample_issue_body_multiple_tables):
        """Primary regex matches 'Hit Count' headers, not the other tables."""
        result = parse_hit_counts(sample_issue_body_multiple_tables)
        assert result.hits_24h == 8
        assert result.hits_7d == 55
        assert result.hits_30d == 200


# =========================================================================
# ERROR PATTERN EXTRACTION
# =========================================================================


class TestErrorPatternExtraction:
    """JSON error blocks embedded in the issue body."""

    def test_extracts_error_message(self, sample_issue_body_with_error_block):
        result = parse_error_pattern(sample_issue_body_with_error_block)
        assert result is not None
        assert "IOException" in result

    def test_extracts_error_from_well_formed(self, sample_issue_body_well_formed):
        result = parse_error_pattern(sample_issue_body_well_formed)
        assert result is not None
        assert "IOException" in result

    def test_no_error_block(self, sample_issue_body_minimal):
        result = parse_error_pattern(sample_issue_body_minimal)
        assert result is None

    def test_empty_body_error(self):
        assert parse_error_pattern("") is None

    def test_none_body_error(self):
        assert parse_error_pattern(None) is None


# =========================================================================
# BUILD LINK EXTRACTION
# =========================================================================


class TestBuildLinkExtraction:
    """Azure DevOps build links in the issue body."""

    def test_extracts_build_link(self, sample_issue_body_with_build_link):
        result = parse_build_link(sample_issue_body_with_build_link)
        assert result is not None
        assert "dev.azure.com" in result

    def test_no_build_link(self, sample_issue_body_no_build_link):
        result = parse_build_link(sample_issue_body_no_build_link)
        assert result is None

    def test_build_link_from_well_formed(self, sample_issue_body_well_formed):
        result = parse_build_link(sample_issue_body_well_formed)
        assert result is not None
        assert "buildId=12345" in result

    def test_empty_body_build_link(self):
        assert parse_build_link("") is None

    def test_none_body_build_link(self):
        assert parse_build_link(None) is None


# =========================================================================
# EDGE CASES
# =========================================================================


class TestEdgeCases:
    """Assorted edge cases that could trip up a naïve parser."""

    def test_non_numeric_values_default_to_zero(self):
        """Non-numeric cell content should not crash the parser."""
        body = (
            "|24-Hour Hit Count|7-Day Hit Count|1-Month Count|\n"
            "|---|---|---|\n"
            "|N/A|unknown|—|\n"
        )
        result = parse_hit_counts(body)
        # Regex requires \\d+, won't match non-numeric → defaults
        assert result.hits_24h == 0
        assert result.hits_7d == 0
        assert result.hits_30d == 0

    def test_very_large_numbers(self):
        """Parser handles very large hit counts without overflow."""
        body = (
            "|24-Hour Hit Count|7-Day Hit Count|1-Month Count|\n"
            "|---|---|---|\n"
            "|999999|1000000|9999999|\n"
        )
        result = parse_hit_counts(body)
        assert result.hits_24h == 999999
        assert result.hits_7d == 1000000
        assert result.hits_30d == 9999999

    def test_table_with_trailing_pipe(self):
        """Standard markdown tables include trailing pipes."""
        body = (
            "|24-Hour Hit Count|7-Day Hit Count|1-Month Count|\n"
            "|---|---|---|\n"
            "|10|50|200|\n"
        )
        result = parse_hit_counts(body)
        assert result.hits_24h == 10
        assert result.hits_7d == 50
        assert result.hits_30d == 200

    def test_body_with_only_whitespace(self):
        result = parse_hit_counts("   \n\n  \t  \n")
        assert result.hits_24h == 0
        assert result.hits_7d == 0
        assert result.hits_30d == 0

    def test_return_type_is_hitcounts(self, sample_issue_body_well_formed):
        from scripts.fetch_issues import HitCounts
        result = parse_hit_counts(sample_issue_body_well_formed)
        assert isinstance(result, HitCounts)

    def test_required_attrs_present(self, sample_issue_body_well_formed):
        result = parse_hit_counts(sample_issue_body_well_formed)
        assert hasattr(result, "hits_24h")
        assert hasattr(result, "hits_7d")
        assert hasattr(result, "hits_30d")


# =========================================================================
# parse_issue_node INTEGRATION  (body → parsed issue → scores)
# =========================================================================


class TestParseIssueNodeIntegration:
    """End-to-end: raw GraphQL node → ParsedIssue with scores."""

    def test_full_pipeline(self):
        from datetime import datetime, timezone
        from scripts.fetch_issues import parse_issue_node

        now = datetime.now(timezone.utc)
        node = {
            "number": 99999,
            "title": "Integration test issue",
            "state": "OPEN",
            "createdAt": (now - __import__("datetime").timedelta(days=5)).isoformat(),
            "updatedAt": (now - __import__("datetime").timedelta(days=1)).isoformat(),
            "body": (
                "|24-Hour Hit Count|7-Day Hit Count|1-Month Count|\n"
                "|---|---|---|\n"
                "|10|50|200|\n"
                "\n"
                "```json\n"
                '{"ErrorMessage": "System.TimeoutException"}\n'
                "```\n"
                "\n"
                "https://dev.azure.com/dnceng/public/_build/results?buildId=7777\n"
            ),
            "author": {"login": "testuser"},
            "labels": {"nodes": [{"name": "Known Build Error"}, {"name": "area-GC"}]},
            "assignees": {"nodes": [{"login": "alice"}]},
            "comments": {
                "nodes": [
                    {
                        "author": {"login": "alice"},
                        "authorAssociation": "MEMBER",
                        "body": "Looking into it",
                        "createdAt": (
                            now - __import__("datetime").timedelta(days=1)
                        ).isoformat(),
                    }
                ]
            },
            "reactions": {"totalCount": 3},
        }

        issue = parse_issue_node(node, "runtime", now)

        # Hit counts parsed correctly
        assert issue.hits_24h == 10
        assert issue.hits_7d == 50
        assert issue.hits_30d == 200

        # Error pattern extracted
        assert issue.error_pattern is not None
        assert "TimeoutException" in issue.error_pattern

        # Build link extracted
        assert issue.build_link is not None
        assert "buildId=7777" in issue.build_link

        # Labels / assignees
        assert "area-GC" in issue.labels
        assert issue.area_label == "area-GC"
        assert "alice" in issue.assignees

        # Comment analysis
        assert issue.human_comment_count == 1

        # Scores are populated
        assert 0 <= issue.urgency_score <= 10
        assert 0 <= issue.staleness_score <= 10
        assert 0 <= issue.neglect_score <= 10
